backend/models/VcsChannel.php
<?php

namespace backend\models;

use Yii;

class VcsChannel extends \common\models\VcsChannelBase {

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->belong = 'cms';
            $this->actived = self::WAIT_APPROVAL_STATUS;
        } else {
            $this->belong = $this->getOldAttribute('belong');
            $this->msisdn = $this->getOldAttribute('msisdn');
        }
        /**
         * "Khi xoá/edit channel (Hay update trạng thái channel 10,11,12 = > 9, 8, -1) thì
        update tất cả các Video (actived=9,10,11,12) về trạng thái
        8: video bị gỡ;  update trường ""note"" text sau ""Channel Disapproved"""
         */
        $oldActived = $this->getOldAttribute('actived');

        if (in_array($oldActived, [10, 11, 12]) && in_array($this->actived, [9, 8, -1]) ) {
            VideoItem::updateAll([
                'actived' => 8,
                'note' => "Channel Disapproved",
            ], [
                'actived' => [9, 10, 11, 12],
                'channel_id' => $this->id,
            ]);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}

common/models/VcsChannel.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "vcs_channel".
 *
 * @property int $id
 * @property string|null $msisdn
 * @property string|null $channel_name
 * @property string|null $channel_avatar
 * @property string|null $header_banner
 * @property int $actived -1: xóa; 0 inactived ; 1: actived
 * @property string|null $description
 * @property int|null $num_follows
 * @property int|null $num_videos
 * @property int|null $is_official
 * @property string|null $slug
 * @property string|null $belong
 * @property string|null $created_from
 * @property string $updated_at
 * @property string|null $created_at
 */
class VcsChannel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vcs_channel';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['actived', 'num_follows', 'num_videos', 'is_official'], 'integer'],
            [['description'], 'string'],
            [['created_from', 'updated_at', 'created_at'], 'safe'],
            [['msisdn'], 'string', 'max' => 30],
            [['channel_name', 'channel_avatar', 'header_banner', 'slug'], 'string', 'max' => 500],
            [['belong'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'msisdn' => 'Msisdn',
            'channel_name' => 'Channel Name',
            'channel_avatar' => 'Channel Avatar',
            'header_banner' => 'Header Banner',
            'actived' => 'Actived',
            'description' => 'Description',
            'num_follows' => 'Num Follows',
            'num_videos' => 'Num Videos',
            'is_official' => 'Is Official',
            'slug' => 'Slug',
            'belong' => 'Belong',
            'created_from' => 'Created From',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
        ];
    }
}

backend/controllers/VcsChannelController.php
<?php

namespace backend\controllers;

use common\core\SuperAppApiGw;
use Yii;
use backend\models\VcsChannel;
use backend\models\VcsChannelSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use common\components\slim\Slim;

/**
 * VcsChannelController implements the CRUD actions for VcsChannel model.
 */
class VcsChannelController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all VcsChannel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VcsChannelSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionApproval()
    {
        $searchModel = new VcsChannelSearch();
        $searchModel->actived = VcsChannelSearch::WAIT_APPROVAL_STATUS;
        $searchModel->showStatusFilter = false;

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('waitApprove', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionListDeleted()
    {
        $searchModel = new VcsChannelSearch();
        $searchModel->actived = VcsChannelSearch::DELETED_STATUS;
        $searchModel->showStatusFilter = false;

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('listDeleted', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single VcsChannel model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = false;
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'isAjax' => Yii::$app->request->isAjax,
        ]);
    }

    /**
     * Creates a new VcsChannel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VcsChannel();
        $model->actived = 0;
        $model->num_follows = 0;
        $model->num_videos = 0;
        $model->actived = VcsChannel::WAIT_APPROVAL_STATUS;

        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $form_values = Yii::$app->request->post();
        // Lay du lieu anh upload len de validate
        // Neu ko co thi xoa
        $form_values['channel_avatar'] = Slim::getImagesFromSlimRequest('channel_avatar');
        $form_values['header_banner'] = Slim::getImagesFromSlimRequest('header_banner');

        if ($model->load($form_values) && $model->save()) {

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Thêm mới "{object}" thành công!', ['object' => Yii::t('backend', 'channel')]));

            $this->processUploadNewImage($model, 'channel_avatar', 'channel_avatar');
            $this->processUploadNewImage($model, 'header_banner', 'header_banner');

            // update cache
            SuperAppApiGw::updateCache('create', 'channel', $model->id);

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }


    }

    /**
     * Updates an existing VcsChannel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $model->loadDefaultValues();
        $form_values = Yii::$app->request->post();

        // Lay du lieu anh upload len de validate
        $form_values['channel_avatar'] = Slim::getImagesFromSlimRequest('channel_avatar');
        $form_values['header_banner'] = Slim::getImagesFromSlimRequest('header_banner');

        if (Yii::$app->request->isPost && $form_values['channel_avatar'])
            $this->processUpdateImage($model, $form_values, 'channel_avatar', 'channel_avatar');

        if (Yii::$app->request->isPost && $form_values['header_banner'])
            $this->processUpdateImage($model, $form_values, 'header_banner', 'header_banner');

        if ($model->load($form_values) && $model->save()) {

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Chỉnh sửa {object} thành công!', ['object' => Yii::t('backend', 'channel')]));

            // update cache
            SuperAppApiGw::updateCache('update', 'channel', $model->id);

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing VcsChannel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));
        $model->actived = VcsChannel::DELETED_STATUS;
        $model->save(false);

        Yii::$app->session->setFlash('info', Yii::t('backend', 'Xóa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

        // update cache
        SuperAppApiGw::updateCache('delete', 'channel', $model->id);

        return $this->redirect(['index']);
    }

    /**
     * Finds the VcsChannel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VcsChannel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VcsChannel::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function processUploadNewImage($model, $imageFieldName, $fileName = null) {

        $images = Slim::getImages($imageFieldName);

        if($images != false && sizeof($images) > 0) {
            $absPath = $model->getAbsImagePath();
            $savePath = Yii::$app->params['media_path']. $absPath;

            $savedFileName = Slim::saveSlimImage2('channel', $images[0], $savePath);

            $model->$imageFieldName = $absPath. $savedFileName;
            $model->update(false, [$imageFieldName]);
        }
    }

    public function processUpdateImage($model, $form_values, $imageFieldName, $fileName = null) {
        if ($form_values['change_'. $imageFieldName] == '1') {
            // $fullSavePath =  Yii::$app->params['sticker_folder']. $absSavePath;

            $oldImagePath = ($model->$imageFieldName)?
                Yii::getAlias('@backend_web'). DIRECTORY_SEPARATOR. $model->$imageFieldName:
                null;

            $images = Slim::getImages($imageFieldName);

            if($images != false && sizeof($images) > 0) {

                $absPath = $model->getAbsImagePath();
                $savePath = Yii::$app->params['media_path']. $absPath;
                $savedFileName = Slim::saveSlimImage2('channel', $images[0], $savePath);
                $model->$imageFieldName = $absPath. $savedFileName;
            } else {
                $model->$imageFieldName = null;

                $model->save();
                // Xoa file anh cu
                if ($oldImagePath && file_exists($oldImagePath))
                    unlink($oldImagePath);
            }
        }
    }

    public function actionBulk(){

        $selection=(array)Yii::$app->request->post('selection'); //typecasting
        $updateIds = $selection;

        if (Yii::$app->request->post('bulk_delete')) {
            $count = VcsChannel::updateAll(['actived' => VcsChannel::DELETED_STATUS ], [
                'id' => $selection
            ]);
            if ($count) {
                Yii::$app->session->setFlash('info', Yii::t('backend', 'Delete {total} items successfully!', [
                    'total' => $count
                ]));

                // update cache
                SuperAppApiGw::updateCache('delete', 'channel', $selection);
            }
        } elseif (Yii::$app->request->post('bulk_active')) {

            $count = VcsChannel::updateAll(['actived' => VcsChannel::ACTIVED_STATUS ], [
                'id' => $selection,
                'actived' => VcsChannel::WAIT_APPROVAL_STATUS,
            ]);

            if ($count) {
                Yii::$app->session->setFlash('info', Yii::t('backend', 'Display all: {total} items', [

backend/views/vcs-channel/_form.php
<?php

use yii\helpers\Html;
use \yii\widgets\ActiveForm;
use yii\helpers\StringHelper;
use yii\helpers\Inflector;

/* @var $this yii\web\View */
/* @var $model backend\models\VcsChannel */
/* @var $title string */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<div class="portlet light portlet-fit portlet-form bordered vcs-channel-form">

    <div class="portlet-body">
        <div class="form-body row">

            <div class="col-md-6">
                <?= $form->field($model, 'channel_name')->textInput(['maxlength' => 500]) ?>
                <?php if (!$model->isNewRecord):?>
                    <?= $form->field($model, 'msisdn')->textInput(['maxlength' => 30, 'readonly' => true]) ?>
                <?php endif;?>

                <?php
                if (!$model->isNewRecord) {

                    $statusArr = \backend\models\VcsChannel::getActiveDefineArr();
                    unset($statusArr[\backend\models\VcsChannel::DELETED_STATUS]);
                    echo $form->field($model, 'actived')->dropDownList($statusArr, [
                        'disabled' => ($model->isNewRecord)? true: false,
                    ]);
                } ?>

                <br />
                <?= $form->field($model, 'is_official')->checkbox() ?>

                <?= $form->field($model, 'description')->textarea(['rows' => 4]) ?>
            </div>
            <div class="col-md-6">

                <?= $this->render('/common/_slim_image_field', [
                    'fieldName' => 'channel_avatar',
                    'itemName' => 'channel', // Vi du: adv, post, post-category de luu rieng tung folder
                    'fieldLabel' => Yii::t('backend', 'Avatar'),
                    'dataMinSize' => '500,500',
                    'dataSize' => '',
                    'dataForceSize' => '',
                    'dataRatio' => '500:500',
                    'model' => $model,
                    'dataWillRemove' => 'avatarWillChange',
                    'dataWillSave' => 'avatarWillChange',
                    'helpBlock' => Yii::t('backend', 'Ratio 500 x 500px(.jpg|png|jpeg)'),
                    'accept' => 'image/jpeg,image/jpg,image/png',
                ]) ?>

                <?= $this->render('/common/_slim_image_field', [
                    'fieldName' => 'header_banner',
                    'itemName' => 'channel', // Vi du: adv, post, post-category de luu rieng tung folder
                    'fieldLabel' => Yii::t('backend', 'Header banner'),
                    'dataMinSize' => '1080,368',
                    'dataSize' => '',
                    'dataForceSize' => '',
                    'dataRatio' => '1080:368',
                    'model' => $model,
                    'dataWillRemove' => 'headerWillChange',
                    'dataWillSave' => 'headerWillChange',
                    'helpBlock' => Yii::t('backend', 'Ratio 1080 x 368px (.jpg|png|jpeg)'),
                    'accept' => 'image/jpeg,image/jpg,image/png',
                ]) ?>
            </div>


            <div class="clearfix"></div>
            <?php /*
            <div class="col-md-6">
                <?= $form->field($model, 'num_follows')->textInput(['readonly' => true]) ?>

            </div>

            <div class="col-md-6">
                <?= $form->field($model, 'num_videos')->textInput(['readonly' => true]) ?>
            </div>
            */?>

        </div>
    </div>
    <div class="portlet-title ">


        <a href="<?= \yii\helpers\Url::to(['index']); ?>" class="btn btn-default btn-sm">
            <i class="fa fa-angle-left"></i> <?= Yii::t('backend', 'Back') ?>                </a>
        &nbsp;&nbsp;&nbsp;
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => 'btn btn-transparent green  btn-sm']) ?>

    </div>
</div>

<?php ActiveForm::end(); ?>
<?php \common\components\slim\SlimAsset::register($this); ?>

backend/views/vcs-channel/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VcsChannelSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="panel panel-default vcs-channel-search">
    <div class="panel-body row">

        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
        ]); ?>

        <div class="col-md-3">
            <?= $form->field($model, 'msisdn') ?>

        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'channel_name') ?>

        </div>
        <?php if ($model->showStatusFilter): ?>
        <div class="col-md-3">
            <?php
            $statusArr = \backend\models\VcsChannel::getActiveDefineArr();
            unset($statusArr[\backend\models\VcsChannel::DELETED_STATUS]);
            echo $form->field($model, 'actived')->dropDownList(
                $statusArr,
                ['prompt' => Yii::t('backend', 'All')]
            ) ?>

        </div>
        <?php endif;?>

        <div class="col-md-3">
            <?php  echo
            $form->field($model, 'is_official')->dropDownList(
                [
                    0 => Yii::t('backend', 'Not Official'),
                    1 => Yii::t('backend', 'Official'),
                ],
                ['prompt' => Yii::t('backend', 'All')]
            );

            ?>

        </div>

        <div class="col-md-12">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
                &nbsp;&nbsp;&nbsp;
                <?= Html::a(Yii::t('backend', 'Reset'), ['index'], ['class' => 'btn btn-default']) ?>

                <?php
                /*<div class="float-right">
                    <?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('backend', 'Create {modelClass}', [
                        'modelClass' => Yii::t('backend', 'Channel')
                    ]),
                        ['create'], ['class' => 'btn btn-info btn-sm']) ?>
                </div>
                 * */?>
                <div class="clearfix"></div>
            </div>

        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/vcs-channel/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\VcsChannel */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => 'Channel',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Channels'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('/css/custom-schedule.css');
?>
<div class="row vcs-channel-create">
    <div class="col-md-12">
        <?= $this->render('_form', [
            'model' => $model,
            'title' => $this->title
        ]) ?>
    </div>
</div>

backend/views/vcs-channel/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\VcsChannel */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
    'modelClass' => 'Channel',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Channels'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update') . ' ' . $model->id;
?>
<div class="row vcs-channel-update">
    <div class="col-md-12">

    <?= $this->render('_form', [
        'model' => $model,
        'title' => $this->title
    ]) ?>

    </div>
</div>

backend/views/vcs-channel/waitApprove.php
<?php


use \yii\grid\GridView;
use awesome\backend\widgets\AwsBaseHtml;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VcsChannelSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Channels');
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('/css/custom-schedule.css');
?>
<div class="row vcs-channel-index">
    <div class="col-md-12">
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
            </div>

            <div class="portlet-body">
                <div class="table-container">
                    <?=Html::beginForm(['vcs-channel/bulk'], 'post', ['id' => 'grid-form',

                    ]);?>
                    <?=Html::submitInput('Delete', ['class' => 'btn btn-warning btn-sm', 'name' => 'bulk_delete',
                        "onclick" => 'if(confirm('.Yii::t('backend', 'Are you sure?').')){
                         return true;
                        }else{
                         return false;
                        }',
                    ]); ?>
                    &nbsp;&nbsp;
                    <?=Html::submitInput('Display All', ['class' => 'btn btn-success btn-sm', 'name' => 'bulk_active',
                        "onclick" => 'if(confirm('.Yii::t('backend', 'Are you sure?').')){
                         return true;
                        }else{
                         return false;
                        }',
                    ]); ?>
                    &nbsp;&nbsp;
                    <?=Html::submitInput('Display Search Engine', ['class' => 'btn btn-success btn-sm', 'name' => 'bulk_active_search',
                        "onclick" => 'if(confirm('.Yii::t('backend', 'Are you sure?').')){
                         return true;
                        }else{
                         return false;
                        }',
                    ]); ?>
                    &nbsp;&nbsp;
                    <?=Html::submitInput('Display Only Owner', ['class' => 'btn btn-sm', 'name' => 'bulk_hide',
                        "onclick" => 'if(confirm('.Yii::t('backend', 'Are you sure?').')){
                         return true;
                        }else{
                         return false;
                        }',
                    ]); ?>
                    <br />
                    <br />
                    <?php
                    Pjax::begin(['formSelector' => 'form#w0', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                    ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterSelector' => 'select[name="per-page"]',
                        'layout' => "{items}\n <div class='form-inline pagination page-size'>" . awesome\backend\grid\AwsPageSize::widget([
                                'options' => [
                                    'class' => 'form-control  form-control-sm',
                                ]]) . '</div> <div class="col-md-6">{pager}</div> <div class="pagination col-md-3 text-right total-count">' . Yii::t('backend', 'Tổng số') . ': <b>' . number_format($dataProvider->getTotalCount()) . '</b> ' . Yii::t('backend', 'bản ghi') . '</div>',
                        // 'filterModel' => $searchModel,
                        'columns' => [
                            //['class' => 'yii\grid\SerialColumn'],
                            [
                                'class' => 'yii\grid\CheckboxColumn',
//                                'headerOptions' => ['width' => '5'],
                            ],

                            [
                                'attribute' => 'channel_avatar',
                                'value' => function ($model) {
                                    return $model->getChannelAvatarUrl();
                                },
                                'format' => ['image', ['height' => '80', 'width' => '80', 'onerror' => "this.src='" . Yii::$app->params['no_image'] . "';"]],
                                'filter' => false,
                                'headerOptions' => ['style' => 'width:100px'],
                            ],
                            [
                                'attribute' => 'header_banner',
                                'value' => function ($model) {
                                    return $model->getHeaderBannerUrl();
                                },
                                'format' => ['image', ['height' => '80', 'onerror' => "this.src='" . Yii::$app->params['no_image'] . "';"]],
                                'filter' => false,
                                'headerOptions' => ['style' => 'width:120px'],
                            ],
                            'msisdn',
                            'channel_name',
                            [
                                'attribute' => 'actived',
                                'value' => function ($model) {
                                    return $model->getActiveName();
                                },

                            ],

                            [
                                'attribute' => 'num_follows',
                                'format' => 'integer'
                            ],
                            [
                                'attribute' => 'num_videos',
                                'format' => 'integer'
                            ],

                            [
                                'attribute' => 'is_official',
                                'format' => 'raw',
                                'value' => function ($object) {
                                    $class = ($object->is_official == 1) ? 'glyphicon-ok' : 'glyphicon-remove';
                                    return '<span class="glyphicon ' . $class . ' icon-is_active"></span>';
                                }
                            ],
                            // 'slug',
                            // 'created_from',
                            'updated_at',
                            'created_at',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'headerOptions' => ['style' => 'width: 110px;', 'class' => 'head-actions'],
                                'contentOptions' => ['class' => 'row-actions'],
                                'buttons' => [
                                    'view' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['view', 'id' => $model->id], [
                                            'class' => '',
                                            'data-target' => '#detail-modal',
                                            'data-toggle' => "modal"
                                        ]);
                                    },
                                ]
                            ],
                        ],
                    ]); ?>

                    <?php
                    Pjax::end();
                    ?>
                    <?= Html::endForm();?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div id="detail-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">

        </div>

    </div>
</div>